export type Tune = {
	-- Misc
	LoadDelay: number,
	AutoStart: boolean,
	AutoFlip: boolean,

	-- Wheel Alignment
	FCamber: number,
	RCamber: number,
	FCaster: number,
	RCaster: number,
	FToe: number,
	RToe: number,

	-- Weight and CG
	Weight: number,
	WeightBSize: { number },
	WeightDist: number,
	CGHeight: number,
	WBVisible: boolean,
	FWheelDensity: number,
	RWheelDensity: number,
	AxleSize: number,
	AxleDensity: number,
	CustomSuspensionDensity: number,

	-- Suspension
	SuspensionEnabled: boolean,
	FSusStiffness: number,
	FSusDamping: number,
	FSusLength: number,
	FPreCompress: number,
	FExtensionLim: number,
	FCompressLim: number,
	FGyroDampening: number,
	RSusStiffness: number,
	RSusDamping: number,
	RSusLength: number,
	RPreCompress: number,
	RExtensionLim: number,
	RCompressLim: number,
	RGyroDampening: number,
	FSusAngle: number,
	FWsBoneLen: number,
	FWsBoneAngle: number,
	FAnchorOffset: { number },
	FSpringOffset: { number },
	RSusAngle: number,
	RWsBoneLen: number,
	RWsBoneAngle: number,
	RAnchorOffset: { number },
	RSpringOffset: { number },
	SusVisible: boolean,
	SusRadius: number,
	SusThickness: number,
	SusColor: string,
	SusCoilCount: number,

	-- Wheel Stabilizer Gyro
	FGyroDamp: number,
	RGyroDamp: number,

	-- Steering
	SteeringType: string,
	SteerRatio: number,
	LockToLock: number,
	Ackerman: number,
	SteerInner: number,
	SteerOuter: number,
	SteerSpeed: number,
	ReturnSpeed: number,
	SteerDecay: number,
	MinSteer: number,
	MSteerExp: number,
	SteerD: number,
	SteerMaxTorque: number,
	SteerP: number,
	FWSteer: string,
	RSteerOuter: number,
	RSteerInner: number,
	RSteerSpeed: number,
	RSteerDecay: number,
	RSteerD: number,
	RSteerMaxTorque: number,
	RSteerP: number,

	-- Engine
	Engine: boolean,
	Horsepower: number,
	IdleRPM: number,
	PearkRPM: number,
	Redline: number,
	PearkSharpness: number,
	CurveMult: number,
	EqPoint: number,
	CompressionRatio: number,

	-- Electric Engine
	Electric: boolean,
	E_Redline: number,
	E_Trans1: number,
	E_Trans2: number,
	E_Horsepower: number,
	EH_FrontMult: number,
	EH_EndMult: number,
	EH_EndPercent: number,
	E_Torque: number,
	ET_EndMult: number,
	ET_EndPercent: number,

	-- Forced Induction
	Turbochargers: number,
	T_Boost: number,
	T_BoostLag: number,
	T2_BoostLag: number,
	Superchargers: number,
	S_Boost: number,
	S_Sensitivity: number,

	-- Drivetrain Misc
	ThrotAccel: number,
	ThrotDecel: number,
	BrakeAccel: number,
	BrakeDecel: number,
	RevAccel: number,
	RevDecay: number,
	RevBounce: number,
	IdleThrottle: number,
	Flywheel: number,
	InclineComp: number,

	-- Drivetrain Config
	Config: string,
	TorqueVector: number,
	DifferentialType: string,
	FDiffSlipThres: number,
	FDiffLockThres: number,
	RDiffSlipThres: number,
	RDiffLockThres: number,
	CDiffSlipThres: number,
	CDiffLockThres: number,
	FDiffPower: number,
	FDiffCoast: number,
	FDiffPreload: number,
	RDiffPower: number,
	RDiffCoast: number,
	RDiffPreload: number,

	-- Traction Control
	TCSEnabled: boolean,
	TCSThreshold: number,
	TCSGradient: number,
	TCSLimit: number,

	-- Transmission
	Clutch: boolean,
	TransModes: { string },
	ClutchMode: string,
	ClutchType: string,
	Stall: boolean,
	ClutchRel: boolean,
	ClutchEngage: number,
	SpeedEngage: number,
	ClutchKick: boolean,
	KickMult: number,
	KickSpeedThreshold: number,
	KickRPMThreshold: number,
	ClutchRPMMult: number,
	TQLock: boolean,
	RPMEngage: number,
	NeutralLimit: boolean,
	NeutralRevRPM: number,
	LimitClutch: boolean,
	AutoShiftMode: string,
	AutoShiftType: string,
	AutoShiftVers: string,
	AutoUpThresh: number,
	AutoDownThresh: number,
	ShiftThrot: number,
	ShiftUpTime: number,
	ShiftDnTime: number,
	FinalDrive: number,
	Ratios: { number },
	FDMult: number,

	-- Brakes
	ABSEnabled: boolean,
	ABSThreshold: number,
	BrakeForce: number,
	BrakeBias: number,
	PBrakeForce: number,
	PBrakeBias: number,
	EBrakeForce: number,

	-- Controls
	Peripherals: {
		MSteerWidth: number,
		MSteerDZone: number,
		ControlLDZone: number,
		ControlRDZone: number,
	},
	Controls: {
		ToggleTCS: EnumItem,
		ToggleABS: EnumItem,
		ToggleTransMode: EnumItem,
		ToggleMouseDrive: EnumItem,
		Throttle: EnumItem,
		Brake: EnumItem,
		SteerLeft: EnumItem,
		SteerRight: EnumItem,
		Throttle2: EnumItem,
		Brake2: EnumItem,
		SteerLeft2: EnumItem,
		SteerRight2: EnumItem,
		ShiftUp: EnumItem,
		ShiftDown: EnumItem,
		Clutch: EnumItem,
		PBrake: EnumItem,
		MouseThrottle: EnumItem,
		MouseBrake: EnumItem,
		MouseClutch: EnumItem,
		MouseShiftUp: EnumItem,
		MouseShiftDown: EnumItem,
		MousePBrake: EnumItem,
		ContlrThrottle: EnumItem,
		ContlrBrake: EnumItem,
		ContlrSteer: EnumItem,
		ContlrShiftUp: EnumItem,
		ContlrShiftDown: EnumItem,
		ContlrClutch: EnumItem,
		ContlrPBrake: EnumItem,
		ContlrToggleTMode: EnumItem,
		ContlrToggleTCS: EnumItem,
		ContlrToggleABS: EnumItem,
	},
}

export type Values = {
	ABS: BoolValue,
	ABSActive: BoolValue,
	AutoClutch: BoolValue,
	Boost: NumberValue,
	BoostSuper: NumberValue,
	BoostTurbo: NumberValue,
	Brake: NumberValue,
	Clutch: NumberValue,
	Gear: NumberValue,
	Horsepower: NumberValue,
	HpBoosted: NumberValue,
	HpElectric: NumberValue,
	HpNatural: NumberValue,
	HpSuper: NumberValue,
	HpTurbo: NumberValue,
	MouseSteerOn: BoolValue,
	PBrake: BoolValue,
	RPM: NumberValue,
	SteerC: NumberValue,
	SteerT: NumberValue,
	TCS: BoolValue,
	TCSActive: BoolValue,
	TCSAmt: NumberValue,
	Throttle: NumberValue,
	Torque: NumberValue,
	TqBoosted: NumberValue,
	TqElectric: NumberValue,
	TqNatural: NumberValue,
	TqSuper: NumberValue,
	TqTurbo: NumberValue,
	TransmissionMode: NumberValue,
	Velocity: NumberValue,
} & Folder

export type Interface = {
	Values: Values,
	Car: ObjectValue,
	IsOn: BoolValue,
	ControlsOpen: BoolValue,
} & ScreenGui

export type Car = {
	DriveSeat: VehicleSeat,

	["A-Chassis Tune"]: {
		README: ModuleScript,
		["A-Chassis Interface"]: Interface,
	} & ModuleScript,

	Body: Model,
	Misc: Model,
	Wheels: {
		FL: BasePart,
		FR: BasePart,
		RL: BasePart,
		RR: BasePart,
	} & Model,
} & Model

return {}
